### ISSUE TITLE
Table for Aquatic Habitats

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#103]

**Comment by ChristopherTracey** [comment]
Draft table of aquatic habitats is now in the tool.

I would love to figure out how to make this one table with the aquatic habitats.

**Comment by dyeany** [comment]
Can it be done easily?

**Comment by ChristopherTracey** [comment]
Perhaps. Maybe it just a two-tiered table.  We have the issue of lentic habitats showing up with the terrestrials.  Maybe we can move the lentic and lotic together somehow.

**Comment by ChristopherTracey** [comment]
Report - if no streams are within the AOI, the report shows an error for the streams table.
Probably just need to check if the table exists and skip the step if it doesn't.  This also seems to add an additional copy of the the terrestrial habitat table into the pdf for some unknown reason if the stream table is missing.

It may be better to fix this by creating the combined terrestrial/aquatic table.

**Comment by ChristopherTracey** [comment]
Let's move this to #110
