### ISSUE TITLE
Habitat Table Updgrade

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#110]
This new issue pulls in #103 and, #102. Closing those and discussion on them can take place here.

I would like to propose that we rebuild the habitat table to something that looks like this:
![img_4740](https://user-images.githubusercontent.com/8216371/31197298-9fe76576-a91e-11e7-96c0-da9c1c57f721.JPG)
_note that the names headings could be more descriptive than this sketch_

This table would have all three habitat types included in one table, grouped by Terrestrial, Lentic, and Lotic categories on the left with different size descriptors between the lentic/terr groups and the lotic.  We would then have the macrogroups present in each major group, with habitats within each. I'm envisioning that the habitats would be in a smaller font size to better emphasize the macrogroups. Area/length totals across the  habitats would show up for each macrogroup (per Cathy's request).  If possible, it would be great to show the macrogroups within the major groups in descending area/length order.

Also, if there are no lentic or lotic habitats within the AOI, we would either not show them or just say something in the table about there being no mapped area of those habitats.

What do we think? I know this is a LaTeX nightmare, but I can't think of a better format.

**Comment by memoore** [comment]
I think this table looks great.  Like you said, this is probably a Latex nightmare, but I can try.

**Comment by dyeany** [comment]
The additional coarse classification will definitely help. Maybe simplify it to start with by just adding the higher classification above the Macrogroup. Something like this:
![20171005_112408](https://user-images.githubusercontent.com/17601144/31235682-1d1d85b0-a9c0-11e7-88e6-ce6e536acc90.jpg)

Maybe this would help overcome the LaTex nightmare.

I do also think that we should list the habitats in descending order as well.

**Comment by ChristopherTracey** [comment]
I can agree with the change on the major groups.

**Comment by ChristopherTracey** [comment]
This looks like its been completed, closing the door.
