### ISSUE TITLE
Priority of Conservation Action Categories: Bar Graph

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#112]
Y-axis scale may not always have a maximum value higher than the highest AIS bar value. We should adjust this axis range to encompass the full range of values in graph. See below:

![image](https://user-images.githubusercontent.com/17601144/31230734-e68ad366-a9b2-11e7-83d1-938882698a29.png)

**Comment by ChristopherTracey** [comment]
We had once talked about quantile scaling these into three categories: 

1. Highest Priority Actions
2. Medium Priority Actions
3. Low Priority Actions

and placing these actions next to the numeric scores. Do we still want to do that?

**Comment by ChristopherTracey** [comment]
This has been removed for now due to the web testing, but we should look at bringing it back based on the level 2 actions.

**Comment by ChristopherTracey** [comment]
Current plan is to leave this out of the tool and display it within the action table.
