### ISSUE TITLE
Table 4: Detailed Actions Table

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#113]
I would suggest using common names in this table to provide more simplicity and to make the tool results more accessible to all users - i.e. not everyone knows _Spizella pusilla_ is  Field Sparrow.

**Comment by ChristopherTracey** [comment]
Yeah, that's the eventually plan--it was limited by SNAMEs only being in the actions table we have available. Thanks for documenting it!

**Comment by ChristopherTracey** [comment]
Fixed in #154
