### ISSUE TITLE
Change "El_Season" to "ELSeason"

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#119]
This should be done in all relevant SQLite tables as well as the GIS data.  We spend a small but significant amount of time in the code changing names back and forth. We really can't deliver the final data products like this.

**Comment by memoore** [comment]
fixed this for now in the sqlite database and script - need to make sure future iterations of the SGCNxPU table are changed to this since source data may be different.  Closing for now and will send link to sqlite DB when I sync script.

**Comment by ChristopherTracey** [comment]
This will probably cause some downstream issues with some of the dataprep scripts (habitat associations for one). We’ll just have to fix stuff as we encounter it.

**Comment by ChristopherTracey** [comment]
We really need to fix this across the board.

**Comment by memoore** [comment]
Changed to ELSeason in sgcnXpu_all table in SQLite database - reopening because this will likely cause problems with script and want to make sure we catch the rest of the ELSeason renaming issues.

**Comment by ChristopherTracey** [comment]
Easily fixed with variable name change and deletion of one line.

I can't find any more occurences of El_Season in the code so I'm closing this.
