### ISSUE TITLE
Change Taxa Groups for Invertebrates

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#127]
Change the displayed groups for the inverts to the following:
- Invertebrate - Bees
- Invertebrate - Beetles
- Invertebrate - Butterflies
- Invertebrate - Crayfishes
- Invertebrate - Dragonflies & Damselflies
- Invertebrate - Moths
- Invertebrate – Mussels                
- Invertebrate - Freshwater Snails
- Invertebrate - Terrestrial Snails 
- Invertebrate – Cave Invertebrates _(includes amphipods, isopods, flatworms, and Springtails) – may group name to include springs_
- Invertebrate - Caddisflies
- Invertebrate - Craneflies
- Invertebrate - Grasshoppers
- Invertebrate - Mayflies
- Invertebrate - Sawflies
- Invertebrate - Spiders
- Invertebrate - Sponges
- Invertebrate - Stoneflies
- Invertebrate - True bugs
Should we just replace this throughout the tool datasets?

**Comment by memoore** [comment]
This is done - accomplished by just adding a "displayname" field in the sqlite database.  will send link to updated database once I'm done with this round of updates and sync the script.

**Comment by ChristopherTracey** [comment]
As I mentioned yesterday, great and simple idea to fix this. Thanks!
