### ISSUE TITLE
SGCN OccHigh / OccFinal prep

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#144]
Need to update 'DataQuality' field with values from Points, Lines and Polygon layers - these did not transfer during the initial data load. Currently working on joining these layers and recalculating values.

Once complete, all features with 'DataQuality' IS NOT NULL will be removed from OccFinal and retained in OccHigh. SGCN_OccFinal will be ready for re-tagging planning units.

NOTE: @ChristopherTracey moved eBird and BBA points have not yet been replaced in the SGCN_Points layer. Do we replace them here as well, erasing any record of the original coordinates?

**Comment by ChristopherTracey** [comment]
No, leave the SGCN points alone. They should be replaced as part of the processing steps to the OccFinal.

**Comment by dyeany** [comment]
Will do. These point occurrences were also replaced in the OccHigh layer, per our previous discussions.

**Comment by ChristopherTracey** [comment]
Great!

**Comment by dyeany** [comment]
Update: 

Attribute Indexes created for 'DataID' field across all SGCN layers. This enabled joins to be made on the OccFinal and OccHigh layers. Working on field calculation for 'DataQuality', 'Last Observed Date', and 'ELSeason'. Field calculation is VERY slow for 270,000+ records.

**Comment by dyeany** [comment]
56%....after 13+ hrs running to calculate DataQuality

**Comment by ChristopherTracey** [comment]
Ouch.

**Comment by dyeany** [comment]
72% at 3:00pm

**Comment by dyeany** [comment]
Field calculation ultimately failed. I have been investigating the join issues this week. I found the following:

DataID Join with SGCN_OccFinal produces the following join errors due to duplicate or missing DataID values across Point, Line and Polygon datasets. This likely had something to do with the length of time calculations were taking and/or failing. 

**Line** (1912 records) –1822 of 277,003 records matched by joining [DataID] from <SGCN_OccFinal> with [DataID] from <SGCN_Line>.
Matching records may not appear in table view due to join validation errors.

**Polygon** (5065 records)– 4640 of 277,003 records matched by joining [DataID] from <SGCN_OccFinal> with [DataID] from <SGCN_Poly>.
Matching records may not appear in table view due to join validation errors.

Cardinality Warning:
Join Validation detected 4686 non-distinct matching records when using [DataID] from <SGCN_OccFinal> with [DataID] from <SGCN_Poly>. 

**Points** (273,620 records) – 268,618 of 277,003 records matched by joining [DataID] from <SGCN_OccFinal> with [DataID] from <SGCN_Point>.
Matching records may not appear in table view due to join validation errors.
Cardinality Warning:
Join Validation detected 515319 non-distinct matching records when using [DataID] from <SGCN_OccFinal> with [DataID] from <SGCN_Point>.

I created a new UniqueID field using a combination of DataID, FeatureID and XY coord. This revealed 19,618 duplicate UniqueIDs (UniqueID_count >1) across 54,678 features. This seems to derive from many missing DataIDs from taxa like bats or fish or multiple bird SGCN with the same DataID from the BBA. I will explore further data combinations to create unique identifiers, looking into ELCODE and LastObsDate incorporation.

For now, @memoore will remerge the orginal SGCN points, lines and polygons into one layer to allow us to redo the replace of moved bird points and ensure DataQuality values were transferred. This will allow us to make a SGCN_OccFinal layer with which we can proceed tool development. 

Will continue to update.

**Comment by memoore** [comment]
I did the merge of the original SGCN points, lines, and polygons again.  The data quality field is now populated.  

There are 342 records in the SGCN points dataset that have null geometry.  A list can be found here: W:\Heritage\Heritage_Projects\1332_PGC_COA\SGCNPoints_NoShape.xlsx

If these are just bad data, we can just delete to clean up the feature class, but if they are supposed to have spatial data, we will have to investigate further and reload these records.

**Comment by ChristopherTracey** [comment]
I think the 342 records should be deleted.

**Comment by dyeany** [comment]
DataQuality filtered features have been loaded into SGCN_OccFinal. Environment field was absent from SGCN_Merge layer, so I am (slowly) running a field calculation on this on the Final feature class. Once this is reconciled and posted, it should be good to go. 

SGCN_OccHigh still needs to be updated. (Note: Use the DeleteFeatures tool to clear a large number of fueatures from a layer. Run time for 270000+ features was 30min.)

**Comment by dyeany** [comment]
SGCN_OccFinal has now been posted to the Working version. It contains 278,160 records.

**Comment by dyeany** [comment]
SGCN_OccHigh has now been posted to the Workig version. It contains 280,255 records.
