### ISSUE TITLE
We should probably add a placeholder for the map

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#158]
This is probably going to be a task for the contractor to do in the final web version, but we may want to have some sort of placeholder (a blank box???) in the prototype so folks don't ask about it repeatedly.

**Comment by dyeany** [comment]
Sure. That makes sense. Definitely for the web enabler. I’d say we shouldn’t invest too much into even a placeholder.

**Comment by memoore** [comment]
Done.
