### ISSUE TITLE
add 'Environment' variable to lu_SGCN?

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#16]
Currently, this is part of the SGCN occurrence datasets. It might serve us a little better to have this be a part of the lu_SGCN table for the following reasons:

- it would one place to maintain the data where we only need 685 records of it instead of >250,000 records. Although, I'm not sure if there are any mistakes in attribution within a particular SGCN, there could be in future.
- We could use this in various scripts such as the habitat associations were we could subset it the terrestrial/aquatic groups. 
- this would allow us to exclude subterranean habitats. [if we want to do this] 

What do you think @dyeany?

**Comment by dyeany** [comment]
I think this makes good sense. It reduces the amount of data within the SGCN occurrence layers and should improve efficiency overall.

**Comment by ChristopherTracey** [comment]
Fixed in #21
