### ISSUE TITLE
SGCN Table Formatting

### ISSUE THREAD

**Issue by memoore** [PNHP/COA#160]
- Move scientific name to parentheses in same column as common name to make additional room
- Add columns for rank - SRANK and GRANK?

**Comment by ChristopherTracey** [comment]
I think we're probably going to go with  the four SWAP priority categories from the plan rather than the heritage ranks. The heritage ranks are integrated into the SWAP priorities though.

**Comment by ChristopherTracey** [comment]
Completed the snames to parentheses issue.

**Comment by ChristopherTracey** [comment]
Added SWAP priority categories.
