### ISSUE TITLE
Are Black Tern and Least Bittern sensitive species?

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#168]
This came up on the call with Cathy yesterday.  We should double check our species lists.

**Comment by dyeany** [comment]
No, neither are sensitive species.

For future reference, the “current” (as of April 2017) sensitive species list is included here:

P:\Conservation Programs\Natural Heritage Program\Data Management\Biotics Database Areas\Element Tracking\current element lists\Sensitive_species_2017-04-17.xlsx

**Comment by ChristopherTracey** [comment]
Thanks!
