### ISSUE TITLE
Double-check ELCODE in SGCNxPU (Eastern Meadowlark)

### ISSUE THREAD

**Issue by memoore** [PNHP/COA#171]
There are several incorrect ELCODE values for Eastern Meadowlark ("AABPBXB2020_b"). Need to fix these and double-check other ELCODE values that were fixed to make sure they are correct.

**Comment by ChristopherTracey** [comment]
What table was this in?  I thought I fixed this previously, but maybe it was incompletely done.

**Comment by memoore** [comment]
This is in the lu_sgcnXpu_all table in the SQLite database.

On Tue, Jan 2, 2018 at 5:22 PM, Christopher Tracey <notifications@github.com

**Comment by memoore** [comment]
Keep eye out for incorrectly labeled ELCODE for Kentucky Warbler as well. ABPBXB2020 is labeled as AABPBXB2020

**Comment by memoore** [comment]
I think this has been taken care of.
