### ISSUE TITLE
Specific Habitat Requirements in report

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#175]
CH wants the specific habitat requirements in the COA report.  @dyeany and I decided to put these in a table in a subsection of the Habitats portion of the report.  Details to follow...

**Comment by ChristopherTracey** [comment]
1. Exported the Habitat Query from the SWAP database.
2. manual fix of Ruffed Grouse do to a crazy setup

**Comment by ChristopherTracey** [comment]
so many data issues like trailing spaces, misspelled names (eg. Euphyes conspicuus, Cordulia shurtleffi), wrong taxonomy (eg. Semiothisa promiscuata), extra spaces in the middle of snames.

**Comment by ChristopherTracey** [comment]
Couldn't find Ephemerella invaria in the list so I deleted it for now.

**Comment by dyeany** [comment]
This was one of the mayflies with taxonomic questions/changes.

--
David Yeany
Conservation Planning Specialist/Ornithologist
Pennsylvania Natural Heritage Program<http://www.naturalheritage.state.pa.us/>
Western Pennsylvania Conservancy<http://www.paconserve.org/123/pa-natural-heritage-program>
800 Waterfront Drive, Pittsburgh, PA 15222
Office: 412-586-2313      Cell: 814-221-4361

**Comment by ChristopherTracey** [comment]
I know. Just documenting.

**Comment by ChristopherTracey** [comment]
This is up and running now, still needs some formatting help.

**Comment by ChristopherTracey** [comment]
We're going to eliminate this seperate table and combine it with the SGCN table in the new landscape report.

**Comment by ChristopherTracey** [comment]
It's joined up, still some formatting to go.  Other Specific habitat table is deleted.
