### ISSUE TITLE
Terrestrial/Lentic Habitat layer filling in the NoData values in Lake Erie

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#18]
Open water habitat in Lake Erie doesn't extend to the planning unit boundary in the 'Habitat_terrestrial_lentic_dissolve' GIS layer. Need to fill in the NoData values with open water.

**Comment by memoore** [comment]
terrestrial/lentic habitat rasters updated to include open water values in Lake Erie.  Datasets can be found here: 
W:\Heritage\Heritage_Projects\1332_PGC_COA\COA_DataToServer.gdb\Habitat_Terrestrial_Lentic
W:\Heritage\Heritage_Projects\1332_PGC_COA\COA_DataToServer.gdb\Habitat_Terrestrial_Lentic_dissolve

**Comment by ChristopherTracey** [comment]
Looks great! Thanks!
