### ISSUE TITLE
Investigate & Remove coarse scale SGCN bird features represented by BBA blocks

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#19]
EOs for birds exist in Biotics with source features represented by BBA blocks. Some of these overlap with finer scale source features (e.g. nests). Investigate how to remove these features to improve habitat association analysis.

**Comment by dyeany** [comment]
Reviewed 159 bird records from PNHP Biotics for inclusion in dataset. 

DataQuality changed to 'BBA Block: Poor Quality' for 36 records. Should be filtered out when data used.
DataQuality changed to 'Independent Source Feature' for 44 records. Should be filtered out when data used. 
21 Independent Source Features retained for SGCN database.

Notes added to 53 records - these represent suggestions for Data Management regarding EO status.

Issues from poor quality data from PNHP birds should be resolved now.

**Comment by ChristopherTracey** [comment]
This is great! Thanks for taking care of it.
