### ISSUE TITLE
Update Habitat_Terrestrial_Lentic rasters to include Lake Erie Classification

### ISSUE THREAD

**Issue by memoore** [PNHP/COA#22]

**Comment by memoore** [comment]
Habitat_Terrestrial_Lentic rasters updated to include Lake Erie classification.  They can be found here: W:\Heritage\Heritage_Projects\1332_PGC_COA\COA_DataToServer.gdb\Habitat_Terrestrial_Lentic
W:\Heritage\Heritage_Projects\1332_PGC_COA\COA_DataToServer.gdb\Habitat_Terrestrial_Lentic_dissolve

**Comment by ChristopherTracey** [comment]
For some reason habitat value 60, which is "North-Central Interior Large River Floodplain" was missing the name in this dataset. I filled it in manually, but we should make sure we don't skip it again.

**Comment by ChristopherTracey** [comment]
So something is wrong with this layer and I can't seem to figure why its happening. When I extract the 'Habitat_Terrestrial_Lentic_dissolve' layer by a mask, the value field is being shifted by one. That is, if a particular pixel has a value of 42 ('South-Central Interior Mesophytic Forest'), the same pixel in derived layer has a value of 43 ('North Atlantic Coastal Plain Pitch Pine Lowland'). This shift seems to happen with other GIS operations as well. @memoore, could this be a result of adding in Lake Erie somehow?

**Comment by ChristopherTracey** [comment]
Actually, I just exported the raster to a new file and the output from that looks ok. I have no clue what's happening.
