### ISSUE TITLE
weighting eBird data lower

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#23]
Hey @dyeany,
 For the habitat association work, it would be possible to weight the eBird Hotspot data a little less in the analysis. This may remove some of those spurious associations. Should I try it?

  Actually, this doesn't necessarily have to apply to the eBird data -- any data set that is sketchy could be weighted less.

**Comment by dyeany** [comment]
Yes, we discussed doing this before and should come up with a scheme for application.



--
David Yeany
Conservation Planning Specialist & Ornithologist
Pennsylvania Natural Heritage Program
Western Pennsylvania Conservancy
800 Waterfront Drive, Pittsburgh, PA 15222
Office: 412-586-2313 Mobile: 814-221-4361


-------- Original message --------

**Comment by ChristopherTracey** [comment]
I'm going to close this for now, as we've talked more more about shifting points to the nearest natural cover as an alternative method..
