### ISSUE TITLE
Update SGCN Priority CAT definitions in SGCN table

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#240]
Text from Chapter 1.3 regarding SGCN prioritization that can be adapted for the COA Tool report:

Table 4. Priority scores for Species of Greatest Conservation Need in Pennsylvania (2015-2025), byprioritization category. 
1 = top priority (red), 6 = lowest priority (green). Species scoring a 1, 2, or 3 in any category are the highest priorities for focused conservation action. R Pennsylvania responsibility species. 
Category 1: Contribute to the conservation of globally or regionally important species. Category 2: Prevent common species from becoming at risk. Category 3: Maintain rare native species. Category 4. Reduce knowledge gaps to better assess conservation status of species. See Chapter 1 for methods. For birds, B = breeding, M = migrant, W = wintering population.

**Comment by ChristopherTracey** [comment]
Do you all think we can color code the cells like the priorities are coded in the SWAP?

**Comment by memoore** [comment]
Added text to describe prioritization values and centered values in table.

**Comment by ChristopherTracey** [comment]
Looks good.
