### ISSUE TITLE
NA values being calculated for AIS

### ISSUE THREAD

**Issue by memoore** [PNHP/COA#242]
NA values are being written into the action table where AIS score should be.

**Comment by ChristopherTracey** [comment]
Testing this earlier today, this seems to be a result of changing the SQLite db. However, checking Molly's db against the version that was working this morning the lu_actions_Level2  tables look to be identical in terms of number of rows and content.  Not sure what's going on, but maybe there's a downstream issue with join from another table in the db.

**Comment by memoore** [comment]
This is fixed. The OccProb values hadn't been updated with 'Probable' instead of 'Medium' yet for wood thrush. I now actually have the updated database on my local sqlite copy and everything seems to be working fine.
