### ISSUE TITLE
Moving eBird points to nearest natural cover for habitat assocations.

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#26]
@dyeany  and I were talking and about a way to potentially fix some of the eBird data in order to produce better habitat associations. One idea is to move the eBird points to the nearest bit of natural cover. 

Here are some steps:

1. Reclass the habitat map where all the 'natural covers' = 1 and the artificial covers are set to NoData.
2. Intersect the eBird points with this map.  Save for later.
3. Take the re-classed habitat map, run a focal stats tool on this for the mean value, don't ignore NoData, circle with a radius of 1. This should make all the edge cells of the natural cover map =no data.
4. Use the IsNull command to make a raster where all the NoData values = 1 and everything else = 0. Reclass this to keep the values of 1 and turn everything else to NoData.
5. use the 'Extract by Mask' tool to get the pull out the edge values from the Natural Cover layer using the results of the previous step as the mask.
6. This should have left us with a raster of just the edge cells. Convert this to a points layer (each cell becomes one point)
7. Take the ebird layer in Step 2, only keep the points that do not overlap the natural cover.
8. Use the 'Near' tool, with a max search distance of 120m, find the near distance between the eBird points and the edge cell points.
9. Export this to a table, and generate an events layer based on the new coordinates, and then export this to a new file. This should have moved all the eBird points that are with 120m of natural cover to the nearest natural cover. These results would need to replaced into the species data and fed into the habitat associations.

Results are below, green triangles are the original points, red squares are the moved points.

![image](https://cloud.githubusercontent.com/assets/8216371/24436683/f4d53fbc-140a-11e7-80d1-e4ce98f8ba47.png)

Some basic descriptive stats for the move distances:
   Minimum:	15.085353 
   Maximum:	119.949882
   Mean:	50.224893
These distances are measured to the center of the pixel, so 15m may be subtracted to get the actual distance moved to reach the cover type.

**Comment by dyeany** [comment]
Where do we stand on this issue? Have the moved data points been posted to the SGCN data layer? Just saw this and thought I'd check.

**Comment by ChristopherTracey** [comment]
It was never integrated into the master dataset. I'm very unclear if it should be (ie. do we maintain the original data or not?).

I should really finish that habitat associations work...

**Comment by dyeany** [comment]
We should maintain the original data - somewhere, but we should have a data layer that functions for the tool, right? So maybe we need another feature class that has all the orginal data and one that has those which have been processed and potentially filtered for use in the COA tool.

**Comment by ChristopherTracey** [comment]
I should rerun this to exclude the peregrine falcon and barn owl from the move away from Ag and Developed covers.  Any other species @dyeany ?

**Comment by dyeany** [comment]
Coming to mind are the following:

Yellow-crowned Night-heron – Urban/suburban riparian woodlots
Black-crowned Night-heron– Urban/suburban riparian woodlots
Bald Eagle - Ag
Purple Martin - Ag

Maybe also…
Eastern Towhee – urban/suburban woodlots
Blackburnian Warbler– urban/suburban woodlots
Hooded Warbler– urban/suburban woodlots

**Comment by ChristopherTracey** [comment]
Thanks. I'll add an exclude for these seven species plus the two that I mentioned above.

**Comment by ChristopherTracey** [comment]
I didn't do the Towhee, Blackburnian, or Hooded--I think they might be fine in the way the analysis was done.  The other six were moved.  

Also, I dropped these species for breeding records only.  Is that the correct way to go?

**Comment by ChristopherTracey** [comment]
I'm also now running this for the BBA Point Counts as well, due to the numerous roadside records.

**Comment by ChristopherTracey** [comment]
Completed. Used in the #121 issue.
