### ISSUE TITLE
Duplicate species names in the species tables

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#27]
In the SGCN data layers (pt, ln, py) there are duplicated entries of some common names.  See this snip of a summarized table:
![image](https://cloud.githubusercontent.com/assets/8216371/24458980/71965e02-1468-11e7-8346-3c6b359bb408.png)
The table reports 98 species instead of the 90 it should. A similar issue on the SNAME column is also the source of the 91 birds and not the 90 that we should have.

Could we check and fix this across all the taxa? @dyeany can you take this on?

**Comment by dyeany** [comment]
This is odd. I will look into it right away.

**Comment by ChristopherTracey** [comment]
I think some of it may be across layers (one spelling in the pts, different spelling in the polys). The summary I showed was from the combined layer.

Thanks!

**Comment by dyeany** [comment]
Can you share with me which combined layer you are using? I can't replicate the duplication on the SGCN_OccFinal_20170306_Diss layer and I'm guessing you're using a different layer.

**Comment by ChristopherTracey** [comment]
Sent under seperate cover.

**Comment by ChristopherTracey** [comment]
Here's some additional issues for the mammals:
"Eastern Small-footed Bat" vs "Eastern Small-footed Myotis"
"Little brown bat" vs "Little Brown Bat"
"Tri-colored bat" vs "Tricolored Bat"

I some of this is likely from the various DBs that went into populating these records. I wish we were better about being standardized.

**Comment by dyeany** [comment]
Funny thing is that I thought we WERE being standardized. I thought I had joined all the names from the same table with standard names...Still looking into all this.

**Comment by dyeany** [comment]
Is lu_SGCN the best list of standardized names?

--
David Yeany
Conservation Planning Specialist/Ornithologist
Pennsylvania Natural Heritage Program<http://www.naturalheritage.state.pa.us/>
Western Pennsylvania Conservancy<http://www.paconserve.org/123/pa-natural-heritage-program>
800 Waterfront Drive, Pittsburgh, PA 15222
Office: 412-586-2313      Cell: 814-221-4361

**Comment by ChristopherTracey** [comment]
It should be as it matches the SWAP database.

**Comment by dyeany** [comment]
Updates have been made as follows and duplicate names have been fixed:
1) Join lu_SGCN with SGCN point, line and polygon feature classes
2) Calculate new field values for:
    TaxaGroup (replaces old domains with new PGC/PFBC approved domains)
    SNAME
    SCOMNAME (except Invertebrates, to maintain more descriptive names)
    SeasonCode (only NULL values)
3) Use Table to dBase tool to create tables for each point, line and polygon layer. Create Table SGCN_merge. Append all 277,811 records to SGCN_merge. 
4) Summarize on SCOMNAME, SNAME. Run Find Identical tool to check for erroneous duplicates and generate tables with only duplicate records. Empty tables were generated indicating no identical SCOMNAME or SNAME values could be found.

Problem fixed. Case #27 closed.

**Comment by ChristopherTracey** [comment]
I was reviewing this and came across a few more outstanding issues:
- in the SGCN_line database, the were four hellbender and mudpuppy records that still had "AA" values instead of "AAAA"
- Eastern Worm Snake in the line database was classified as AR, similar issue for the wood turtle
- few other odonates had this issue as well.

**Comment by dyeany** [comment]
I see this. I must have overlooked these few records. They have all been updated with the new  Taxa Group codes.

**Comment by ChristopherTracey** [comment]
Oh, I updated them as well. I'm also finding a lot of blank SNames.

**Comment by dyeany** [comment]
I see null SNAME and SCOMNAME values in the point class only. However, this does not make sense because I recalculated both fields across all three layers. I'll fix this.



--
David Yeany
Conservation Planning Specialist & Ornithologist
Pennsylvania Natural Heritage Program
Western Pennsylvania Conservancy
800 Waterfront Drive, Pittsburgh, PA 15222
Office: 412-586-2313 Mobile: 814-221-4361


-------- Original message --------

**Comment by ChristopherTracey** [comment]
So there are 11 records of Tiger Salamanders (AAAAA01140) in the pt layer.  These are not considered an SGCN, so I deleted them.  There were five records of Eastern Mud salamanders (AAAAD13010) that were missing snames and scomname, which I added back.

**Comment by ChristopherTracey** [comment]
We have 10 records of a frog from the PARS dataset that has an ELCODE of AAABH01400. I don't think this ELCODE exists as it doesn't seem to exist in any of the databases.

**Comment by ChristopherTracey** [comment]
There were eight records of the Eastern mud turtle (ARAAE01050) that didn't have the s/c names.  Fixed

**Comment by dyeany** [comment]
I added "Eastern Sulphur" as SCOMNAME for Ephemeralla invaria. A selection for NULL SNAME or SOMNAME values resulted in 0 selected records. I'll close this issue now. If something was missed let me know.

**Comment by dyeany** [comment]
AAABH01400 is Lithobates kauffeldi Atlantic Coast Leopard Frog.

**Comment by ChristopherTracey** [comment]
Really? Is this new species Matt S and crew discovered in NY?

**Comment by ChristopherTracey** [comment]
80 records of ABPBX05010, replaced s/c name with Black-and-white Warbler
