### ISSUE TITLE
Build a master habitat table with lookup codes for all habitats

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#46]
I think we can combine the terrestrial and aquatic codes into one table and just subset via the code.  

The table should have:

- formation
- macrogroup
- habitat
- type (lotic,lentic,terrestrial)

We'll have to replace this code into the various habitat layers that have already been created.

**Comment by ChristopherTracey** [comment]
This has been created and is now sitting in the sqlite db.  The habitatcode is based on a four digit code (lake, terr, strm) for the three types extended with the gridcode or class value from the original dataset. Next steps are to build a translation table and attribute the various layers with that.

**Comment by memoore** [comment]
I'm working on rebuilding the habitat x PU table to match the habitatcode that Chris created.

**Comment by ChristopherTracey** [comment]
Terrestrial/Palustrine/Lake habitats names are now supplied via a lookup table and code has been updated to reflect these changes in names.

Still need to complete update for Lotic habitats.

**Comment by ChristopherTracey** [comment]
Completed.
