### ISSUE TITLE
Contact info for the COA Report

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#57]
The last part of the metadata should include something like this:
![img_4246](https://user-images.githubusercontent.com/8216371/30341550-689ba372-97c4-11e7-9555-68aa00b157fb.png)

We should also include the PGC and PFBC shields next to their names (rather than at the top of the page).

**Comment by memoore** [comment]
Included contact information and PGC/PFBC shields at bottom of PDF output.
