### ISSUE TITLE
lu_HabitatName table

### ISSUE THREAD

**Issue by memoore** [PNHP/COA#60]
duplicate system names (ex: Acidic Cliff and Talus)

**Comment by ChristopherTracey** [comment]
The reason behind this is that there are three types of Acidic Cliff and Talus in PA:
1. North-Central Appalachian Cliff and Talus
2. Central Interior Acidic Cliff and Talus
3. Laurentian-Acadian Acidic Cliff and Talus
There's actually two more types that are in the NE outside PA.  The Ecological System name that NS uses has the geographic specificity added in, whereas the habitat name that was used dropped it, as the systems are not all that different based on wildlife use.

We can add these names back into the the table if we really want to. I'm not sure if its necessary for the purposes of the tool (especially in terms of reducing complexity by using macrogroups).

**Comment by ChristopherTracey** [comment]
This was fixed a while back.
