### ISSUE TITLE
UPDATE COA.DBO.SGCN_OccFinal and/or COA.DBO.SGCN_OccHigh

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#61]
Both of these feature classes are still empty in the feature dataset. Can we update at least the OccHigh layer with the polygon SGCN data that is currently being used to generate SGCNxPU tables? 

@memoore are these data currently on your local drive? I just want to make sure that what we are currently using is also in the "official" COA database as one combined layer. 

Also, @ChristopherTracey I want to use this to check the PARS date question. And @ChristopherTracey we could add the eBird records you spatially adjusted to this layer while retaining them in the original COA.DBO.SGCN_Point layer. What do you think?

**Comment by ChristopherTracey** [comment]
We can do that regarding the the eBird records. I'm looking for them now.

**Comment by memoore** [comment]
OccHigh layer and OccFinal layers were updated.

OccHigh includes all occurrences collected.
OccFinal includes filtered occurrences and is what was used to populate planning units with "High"
