### ISSUE TITLE
COA Mapping Results Reports - Attribute & Format Considerations

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#96]
I'm opening this issue to generate a thread for tracking aspects of adjusting attribute and formatting for the tool results output PDF reports.

To begin, here are some thoughts on the examples sent out on 9/29/2017:

1)	What if we list all SGCN by OccProb (High, Med, Low) in the species table, but only provide detailed actions for High & Med?

2) The term "macrogroup" likely needs to be replaced with a more general synonym in the habitat section or much further explanation will need to be added, as most users likely do not know what a macrogroup is.

3) The list of detailed actions are somewhat meaningless unless the user knows which species they are targeting. For example, "Allow succession of old fields to support the species." isn't something one would want to do without understanding which species are going to benefit.

4) AIS - We ought to include more explanation on this or a link to further explanation. I would be cautious about revealing too much detail to the user and opening a can of worms here, though. Also, had we discussed a categorical AIS or at least displaying the bar graph as categories? I'd be on the fence about that right now, but we ought to consider it as an option.

**Comment by ChristopherTracey** [comment]
regarding the third item--I'm working on this now. The current version was just a placeholder load-in.

**Comment by ChristopherTracey** [comment]
On 1)  We could consider showing all the probabilities in the table as suggested and then only having the actions the High/Med.  We didn't receive any negative comments about the format with the low value in the paragraph today, but I kinda like the idea of everything in the table better.  Let's discuss more.
